dependencies:
  - beautifulsoup4==4.12.3
  - Cartopy==0.22.0
  - ipywidgets==8.0.4
  - matplotlib==3.7.2
  - networkx==3.1
  - numpy==1.23.5
  - pandas==2.0.3
  - Requests==2.31.0
  - scipy==1.12.0
  - seaborn==0.13.2
  - tqdm==4.65.0
  - watermark==2.4.3
  - wget==3.2
